# Generated by Django 3.2.9 on 2021-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_doors', models.IntegerField()),
                ('engine', models.CharField(max_length=256)),
                ('roof', models.BooleanField()),
                ('production', models.DateField()),
            ],
        ),
    ]
